apiVersion: v1
kind: Service 
metadata:
  name: engineering-api
  labels:
    app: engineering-api
spec:
  type: NodePort
  selector:
    app: engineering-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  